[project]
name = "meshtastic-kml-kmz-exporter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "meshtastic>=2.7.7",
    "simplekml>=1.3.6",
]
